package com.jmtennant.sudoku.SudokuSolver.helper;

public abstract class BoardCheck implements VerifySolution {

	/**
	 * Holds output generated by checkBoard() for access by getOutput()
	 */
	protected String output;

	@Override
	public String getOutput() {
		return output;
	}

}
